### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by silverfox0000** [GnomedDev/tts-service#1]
Hello Again.

Log [here](https://pastebin.com/WdJ2NXTw)
Password: qrD6qyD01w

P.S I Read the Dockerfile and command `apt-get install -y libclang-dev libespeak-ng1` but i will already installed it and same error

**Comment by GnomedDev** [comment]
Please contact me via discord (Gnome!#6669) instead of opening a load of github issues across the TTS Bot projects.
